// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement("h1", undefined, "Proffy"), root);
}

export {
  
}
/* root Not a pure module */
